// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVqwU0NIn__EwuZnU_k-d2-qPGMWc8dQw',
    appId: '1:406428556163:web:3ff40befff69c970f734b6',
    messagingSenderId: '406428556163',
    projectId: 'smetasphere',
    authDomain: 'smetasphere.firebaseapp.com',
    storageBucket: 'smetasphere.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwlK-RC0TCQrAsrRgrl3QfsEsMusZh-b8',
    appId: '1:406428556163:android:6da562290d0085baf734b6',
    messagingSenderId: '406428556163',
    projectId: 'smetasphere',
    storageBucket: 'smetasphere.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg2o9cRtBvGQ7m66Ut-munwDEIh5AIL-E',
    appId: '1:406428556163:ios:50f7735d8e795d78f734b6',
    messagingSenderId: '406428556163',
    projectId: 'smetasphere',
    storageBucket: 'smetasphere.firebasestorage.app',
    iosBundleId: 'com.example.smetasphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg2o9cRtBvGQ7m66Ut-munwDEIh5AIL-E',
    appId: '1:406428556163:ios:50f7735d8e795d78f734b6',
    messagingSenderId: '406428556163',
    projectId: 'smetasphere',
    storageBucket: 'smetasphere.firebasestorage.app',
    iosBundleId: 'com.example.smetasphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVqwU0NIn__EwuZnU_k-d2-qPGMWc8dQw',
    appId: '1:406428556163:web:cf4be4525f7c12f3f734b6',
    messagingSenderId: '406428556163',
    projectId: 'smetasphere',
    authDomain: 'smetasphere.firebaseapp.com',
    storageBucket: 'smetasphere.firebasestorage.app',
  );
}
